# Utiliser une image CentOS de base optimisée
FROM centos:latest

LABEL maintainer="Groupe5"
LABEL description="Image CentOS avec Apache (httpd)."

# Ajouter un miroir de dépôt alternatif fiable
RUN rm -f /etc/yum.repos.d/* && \
    curl -o /etc/yum.repos.d/CentOS-Base.repo https://vault.centos.org/8.5.2111/BaseOS/x86_64/os/

# Mettre à jour le système, installer Apache, et supprimer les fichiers de cache dans une seule commande pour réduire les couches d'image
RUN yum update -y && \
    yum install -y httpd && \
    yum clean all && \
    rm -rf /var/cache/yum

# Créer un utilisateur non-root pour exécuter le serveur web afin d'améliorer la sécurité
RUN useradd -r -d /var/www -s /sbin/nologin httpuser && \
    mkdir -p /var/www/html && \
    chown -R httpuser:httpuser /var/www/html

# Exposer le port HTTP
EXPOSE 80

# Utiliser l'utilisateur non-root pour exécuter Apache
USER httpuser

# Définir Apache comme service à démarrer avec le conteneur
CMD ["/usr/sbin/httpd", "-D", "FOREGROUND"]

