# Utiliser une image Ubuntu de base
FROM ubuntu:latest

LABEL maintainer="Groupe5"
LABEL description="Image Ubuntu avec Nginx."

# Mettre à jour le système et installer Nginx
RUN apt-get update && apt-get install -y nginx

# Nettoyer les caches apt pour réduire la taille de l'image
RUN apt-get clean && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*

# Exposer le port HTTP
EXPOSE 80

# Définir Nginx comme service à démarrer avec le conteneur
CMD ["nginx", "-g", "daemon off;"]

